### ISSUE TITLE
ShadowSocksR Plus+节点是V2RAY的时候启动失败

### ISSUE THREAD

**Issue by boiio** [Einic/HiWiFi-HC5661A-Openwrt#3]
用ssh登进去重启服务提示Illegal instruction
当节点是ssr时无问题
该如何解决？

**Comment by boiio** [comment]
已自编译了lean的lede，结帖。

**Comment by dragon0629** [comment]
@boiio 大佬好，请问有你编译的固件嘛，5561A支持V2RAY的，和你问题一样，无法解决V2RAY使用不能的问题。求发一份OJZ

**Comment by boiio** [comment]
[https://drive.google.com/open?id=1fY4QNcwka7Z5ZxNn6McKHo1LZI-qy3Qp](url)
不确定这个是不是了，因为编译完名字都一样的，你可以刷上试试。

**Comment by boiio** [comment]
> @boiio 大佬好，请问有你编译的固件嘛，5561A支持V2RAY的，和你问题一样，无法解决V2RAY使用不能的问题。求发一份OJZ

[https://drive.google.com/open?id=1fY4QNcwka7Z5ZxNn6McKHo1LZI-qy3Qp](url)
不确定这个是不是了，因为编译完名字都一样的，你可以刷上试试。

**Comment by yiailake** [comment]
恩山有编译好的固件，支持5561A，https://www.right.com.cn/forum/thread-3751521-1-1.html
